apiVersion: apps/v1
kind: Deployment
metadata:
  name: pegaleazr
  labels:
    app: pegaleazr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pegaleazr
  template:
    metadata:
      labels:
        app: pegaleazr
    spec:
      containers:
      - name: pegale
        image: acreu1c002bnnidev01.azurecr.io/pegale:1
        ports:
        - containerPort: 8080
